### ISSUE TITLE
PhoneAccount connection service requires BIND_TELECOM_CONNECTION_SERVICE permission

### ISSUE THREAD

**Issue by bmp123** [wazo-pbx/react-native-callkeep#16]
I can't start my app with this error PhoneAccount connection service requires BIND_TELECOM_CONNECTION_SERVICE permission. I get all permissions. How can I fix it?

**Comment by bmp123** [comment]
`2019-02-12 17:50:02.248 14751-14820/com.onlinepbx E/unknown:ReactNative: Exception in native call
    java.lang.SecurityException: PhoneAccount connection service requires BIND_TELECOM_CONNECTION_SERVICE permission.
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at com.android.internal.telecom.ITelecomService$Stub$Proxy.registerPhoneAccount(ITelecomService.java:1048)
        at android.telecom.TelecomManager.registerPhoneAccount(TelecomManager.java:1018)
        at io.wazo.callkeep.RNCallKeepModule.registerPhoneAccount(RNCallKeepModule.java:241)
        at io.wazo.callkeep.RNCallKeepModule.<init>(RNCallKeepModule.java:85)
        at io.wazo.callkeep.RNCallKeepPackage.createNativeModules(RNCallKeepPackage.java:33)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:85)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1173)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1143)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1085)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:117)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.telecom.PhoneAccountRegistrar.registerPhoneAccount(PhoneAccountRegistrar.java:662)
        at com.android.server.telecom.TelecomServiceImpl$1.registerPhoneAccount(TelecomServiceImpl.java:446)
        at com.android.internal.telecom.ITelecomService$Stub.onTransact(ITelecomService.java:237)
        at android.os.Binder.execTransact(Binder.java:731)
`

**Comment by manuquentin** [comment]
Hi @bmp123,
Please follow this step in the installation documentation: https://github.com/wazo-pbx/react-native-callkeep/blob/master/docs/android-installation.md#android-common-step-installation

**Comment by bmp123** [comment]
@manuquentin Hi, thank you for your answer. I do all from android installing documentation, but always have this error... What it's mean? Maybe you know another steps to fix it?

**Comment by bmp123** [comment]
buildToolsVersion = "26.0.2"
minSdkVersion = 21
compileSdkVersion = 26
targetSdkVersion = 26
supportLibVersion = "27.1.1"
Android: 9 Pie

**Comment by bmp123** [comment]
it's work only in production build

**Comment by manuquentin** [comment]
Hi @bmp123,
You can take a look at [our demo](https://github.com/wazo-pbx/wazo-react-native-demo) and check what's different from your configuration.

**Comment by bmp123** [comment]
Hi, close this issue. now it's works for me.

**Comment by ehp006** [comment]
@bmp123 ,
What did you change to fix the issue for you ?

**Comment by Arlen22** [comment]
> Even though I had add the permission on my AndroidManifest.xml I still had to add this extra bit to it:
> 
> ```xml
> <service android:name="com.my.app.RNCallConnectionService"
>     android:permission="android.permission.BIND_TELECOM_CONNECTION_SERVICE">
>     <intent-filter>
>         <action android:name="android.telecom.ConnectionService" />
>     </intent-filter>
> </service>
> ```

-- StackOverflow: https://stackoverflow.com/a/49857261/258482

**Comment by tushar04** [comment]
I'm also getting the same issue for android, iOS working fine. @bmp123 what was the solution you tried to get rid of this?

**Comment by iim-norse** [comment]
I'm also getting the same issue for android. solution ?

**Comment by iim-norse** [comment]
I think this: https://github.com/react-native-webrtc/react-native-callkeep/issues/289#issuecomment-1113102613

**Comment by Parmar-Bansi** [comment]
> Hi, close this issue. now it's works for me.

give share your way for this issue ..still same error msg ..
